name: On Pull Request
on:
  pull_request:
  workflow_dispatch:

jobs:
  build_java_17:
    name: Compile (Java 17)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: maven
        run: mvn package
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: "MissileWarfare (Java 17)"
          path: |
            target/*.jar
            !target/original-*
          if-no-files-found: error
  build_java_16:
    name: Compile (Java 16)
    runs-on: ubuntu-latest
    needs: [ build_java_17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: maven
        run: mvn package
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: "MissileWarfare (Java 16)"
          path: |
            target/*.jar
            !target/original-*
          if-no-files-found: error
  build_java_8:
    name: Compile (Java 8)
    runs-on: ubuntu-latest
    needs: [ build_java_16 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: maven
        run: mvn package --file pom/pom-j8.xml
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: "MissileWarfare (Java 8)"
          path: |
            pom/target/*.jar
            !pom/target/original-*
          if-no-files-found: error
  build_MC_1_18_2:
    name: Compile (MC 1.18.2)
    runs-on: ubuntu-latest
    needs: [ build_java_17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: maven
        run: mvn package --file pom/pom-1.18.2.xml
  build_MC_1_17_1:
    name: Compile (MC 1.17.1)
    runs-on: ubuntu-latest
    needs: [ build_MC_1_18_2, build_java_16 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: maven
        run: mvn package --file pom/pom-1.17.1.xml
  build_MC_old:
    name: Compile (MC 1.13.2-1.16.5)
    runs-on: ubuntu-latest
    needs: [ build_MC_1_17_1, build_java_8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: 1.16.5
        run: mvn package --file pom/pom-1.16.5.xml
      - name: 1.15.2
        run: mvn clean package --file pom/pom-1.15.2.xml
      - name: 1.14.4
        run: mvn clean package --file pom/pom-1.14.4.xml
      - name: 1.13.2
        run: mvn clean package --file pom/pom-1.13.2.xml
